site_name: Erweiterte Suche
docs_dir: .
use_directory_urls: true

theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - macros
  - include-markdown

nav:
  - Übersicht: index.md
  - Editionen: editionen.md
  - Installation: 
    - installation/index.md
    - Anforderungen: 
      - Systemanforderungen: installation/anforderungen/index.md
      - Kompatibilität: installation/anforderungen/kompatibilitaet.md
      - Vorbereitungen: installation/anforderungen/vorbereitungen.md
    - Neuinstallation:
      - installation/anforderungen/index.md
      - Vorbereitung: installation/anforderungen/vorbereitung.md
      - Modul hinzufügen: installation/anforderungen/modul_hinzufuegen.md
      - Verwendung eigener Themes: installation/anforderungen/verwendung_eigener_themes.md
      - Providerspezifische Installation: installation/anforderungen/providerspezifische_installation.md
      - Modul im Shop aktivieren: installation/anforderungen/modul_im_shop_aktivieren.md
      - Shopanpassungen installieren: installation/anforderungen/shopanpassungen_installieren.md
      - TMP Ordner leeren: installation/anforderungen/tmp-ordner_leeren.md
      - Lizenz eintragen: installation/anforderungen/lizenz_eintragen.md
      - Cronjob einrichten: installation/anforderungen/cronjob_einrichten.md
      - Updatefähigkeit: installation/anforderungen/updatefaehigkeit.md
  - Handbuch: 
    - 030_Handbuch/inhalte.md
    - Ergebnisanalyse: 030_Handbuch/ergebnisanlyse.md
  - Changelog: changelog.md
  - Support: 
    - 050_Support/index.md
    - Lizenzen: 050_Support/licenses.md

extra:
  modulename:    "erweiterte Suche"
  modulefolder:  "extsearch"
  metadataident: "d3_extsearch"
  modcfgident:   "d3_extsearch"
  composerident: "d3/extsearch"